#!/bin/bash


_python_() {
    python3${pVer%.*} -c "$1"
}

_ROYALBOT_MAIN() {
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "https://github.com/ROYALBOY871/Userbot"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_royal_repo () {
    local hrepo
    hrepo=`echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnM=" | base64 -d`
    echo "$rlink"
}

_royal_zip () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_ROYALBOT_PLUG() {
    local hrepo=$(_hell_repo)
    $(_python_ 'from git import Repo
import sys
_UPSTREAM_ = "'$hrepo'"
_BRANCH_ = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", _UPSTREAM_)
origin.fetch()
repo.create_head(_BRANCH_, origin.refs[_BRANCH_])
repo.heads[_BRANCH_].checkout(True) ')
}

_starter () {
    local royalpath
    royalpath="Plugins.zip"
    echo "••• DOWNLOADING ROYALBOT •••"
    wget -q $(_hell_zip) -O "$royalpath"
    HELLPATH=$(zipinfo -1 "$royalpath" | grep -v "/.");
    unzip -qq "$royalpath"
    rm -rf "$royalpath"
    # _ROYALBOT_MAIN
    cd $ROYALPATH
    # _ROYALBOT_PLUG
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "••• STARTING ROYALBOT •••"
    python3 -m Royalbot
}

_starter

